import { autoUpdater } from 'electron-updater'

// autoUpdater.forceDevUpdateConfig = true
//
// Don't override the feed URL here. Upstream Hayase pointed it at
// `api.hayase.watch/files` (their CDN-fronted update server) which makes
// this fork think upstream's v6.4.61 is "latest" and silently refuses to
// upgrade users to our newer releases:
//
//   "Update for version 6.4.81 is not available
//    (latest version: 6.4.61, downgrade is disallowed)."
//
// With no explicit setFeedURL call, electron-updater falls back to
// app-update.yml in the packaged resources. That file is generated by
// electron-builder from the publish: block in electron-builder.yml,
// which we already pointed at github.com/nickEatsBread/hayase. Result:
// the autoUpdater reads our latest.yml from the right repo's releases.
autoUpdater.checkForUpdates()

export default class Updater {
  hasUpdate = false

  constructor () {
    autoUpdater.on('update-downloaded', () => {
      this.hasUpdate = true
    })

    setInterval(() => autoUpdater.checkForUpdates(), 1000 * 60 * 30).unref() // 30 mins
  }

  install (forceRunAfter = false) {
    if (this.hasUpdate) {
      autoUpdater.quitAndInstall(true, forceRunAfter)
      this.hasUpdate = false
      return true
    }
    return false
  }
}
